export type ThemeColor = 
  | 'primary' 
  | 'primary-contrast' 
  | 'secondary' 
  | 'secondary-contrast' 
  | 'accent' 
  | 'accent-contrast' 
  | 'success' 
  | 'success-contrast' 
  | 'warning' 
  | 'warning-contrast' 
  | 'danger' 
  | 'danger-contrast' 
  | 'surface'
  | 'surface-contrast'
  | 'surface2'
  | 'surface2-contrast'
  | 'surface3'
  | 'surface3-contrast'
  | 'surface4'
  | 'surface4-contrast'
  